/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfercheckRouteImport } from './routes/transfercheck'
import { Route as SurgisimRouteImport } from './routes/surgisim'
import { Route as ImaginelabsRouteImport } from './routes/imaginelabs'
import { Route as DexforgeRouteImport } from './routes/dexforge'
import { Route as CabledataRouteImport } from './routes/cabledata'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TransfercheckRoute = TransfercheckRouteImport.update({
  id: '/transfercheck',
  path: '/transfercheck',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgisimRoute = SurgisimRouteImport.update({
  id: '/surgisim',
  path: '/surgisim',
  getParentRoute: () => rootRouteImport,
} as any)
const ImaginelabsRoute = ImaginelabsRouteImport.update({
  id: '/imaginelabs',
  path: '/imaginelabs',
  getParentRoute: () => rootRouteImport,
} as any)
const DexforgeRoute = DexforgeRouteImport.update({
  id: '/dexforge',
  path: '/dexforge',
  getParentRoute: () => rootRouteImport,
} as any)
const CabledataRoute = CabledataRouteImport.update({
  id: '/cabledata',
  path: '/cabledata',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabledata': typeof CabledataRoute
  '/dexforge': typeof DexforgeRoute
  '/imaginelabs': typeof ImaginelabsRoute
  '/surgisim': typeof SurgisimRoute
  '/transfercheck': typeof TransfercheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabledata': typeof CabledataRoute
  '/dexforge': typeof DexforgeRoute
  '/imaginelabs': typeof ImaginelabsRoute
  '/surgisim': typeof SurgisimRoute
  '/transfercheck': typeof TransfercheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabledata': typeof CabledataRoute
  '/dexforge': typeof DexforgeRoute
  '/imaginelabs': typeof ImaginelabsRoute
  '/surgisim': typeof SurgisimRoute
  '/transfercheck': typeof TransfercheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cabledata'
    | '/dexforge'
    | '/imaginelabs'
    | '/surgisim'
    | '/transfercheck'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cabledata'
    | '/dexforge'
    | '/imaginelabs'
    | '/surgisim'
    | '/transfercheck'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cabledata'
    | '/dexforge'
    | '/imaginelabs'
    | '/surgisim'
    | '/transfercheck'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CabledataRoute: typeof CabledataRoute
  DexforgeRoute: typeof DexforgeRoute
  ImaginelabsRoute: typeof ImaginelabsRoute
  SurgisimRoute: typeof SurgisimRoute
  TransfercheckRoute: typeof TransfercheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfercheck': {
      id: '/transfercheck'
      path: '/transfercheck'
      fullPath: '/transfercheck'
      preLoaderRoute: typeof TransfercheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgisim': {
      id: '/surgisim'
      path: '/surgisim'
      fullPath: '/surgisim'
      preLoaderRoute: typeof SurgisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imaginelabs': {
      id: '/imaginelabs'
      path: '/imaginelabs'
      fullPath: '/imaginelabs'
      preLoaderRoute: typeof ImaginelabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dexforge': {
      id: '/dexforge'
      path: '/dexforge'
      fullPath: '/dexforge'
      preLoaderRoute: typeof DexforgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabledata': {
      id: '/cabledata'
      path: '/cabledata'
      fullPath: '/cabledata'
      preLoaderRoute: typeof CabledataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CabledataRoute: CabledataRoute,
  DexforgeRoute: DexforgeRoute,
  ImaginelabsRoute: ImaginelabsRoute,
  SurgisimRoute: SurgisimRoute,
  TransfercheckRoute: TransfercheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
